### ISSUE TITLE
Can't clone repo to windows due to CON.md

### ISSUE THREAD

**Issue by carco5a** [1arry1iu/archetype#1]
HI. I just wanted to let you know that this repo won't be able to be cloned to a Windows based OS as a file cannot be named "CON" on that platform. Git errors out with the following:

`error: invalid path 'Hack/CON.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
`

**Comment by 1arry1iu** [comment]
Thank you. I've just changed the name of the file.
